config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]

  namespace :admin do
    resources :users, only: [:new, :index, :create, :destroy, :show]
    resources :categories, only: [:index, :new, :create, :destroy]
    resources :gifs, only: [:new, :index, :create, :destroy]
    resources :favorites, only: [:new, :create, :destroy]
  end

  resources :gifs, only: [:show, :index]

  resources :favorites, only: [:new, :create, :destroy]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  root 'users#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :gifs, dependent: :delete_all
  validates :search_term, presence: true, uniqueness: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :gif
end

app/models/gif.rb
class Gif < ActiveRecord::Base
  belongs_to :category
  validates :image_path, presence: true
  has_many :users, through: :favorite
  has_many :favorites, dependent: :delete_all
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, :email, :password, presence: true
  validates :email, uniqueness: true
  has_many :gifs, through: :favorite
  has_many :favorites
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: '/public/404' unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path
      flash[:success] = "New category created!"
    else
      flash.now[:info] = "Category exists, please try again"
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.gifs.count == 0
      @category.destroy
      redirect_to admin_categories_path
      flash[:success] = "Category successfully deleted!"
    else
      redirect_to admin_categories_path
      flash[:danger] = "Category still has GIFs!"
    end
  end

  private

  def category_params
    params.require(:category).permit(:search_term)
  end
end

app/controllers/admin/favorites_controller.rb
class Admin::FavoritesController < Admin::BaseController

  def new

  end

  def create
    @gif = Gif.find(params[:gif_id])
    @favorite = Favorite.create(user_id: current_user.id, gif_id: @gif.id)
    redirect_to user_path(current_user)
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to user_path(current_user)
  end
end

app/controllers/admin/gifs_controller.rb
class Admin::GifsController < Admin::BaseController

def index
  @categories = Category.all
end

def new
  @categories = Category.all
end

def create
  # @category = Category.find_by(search_term: params[:search_term])
  # @gif = Gif.new(image_path: Giphy.random(@category.search_term).image_url.to_s, category_id: @category.id)
  if Category.find_by(search_term: params[:search_term])
    @category = Category.find_by(search_term: params[:search_term])
    search_term = @category.search_term
    @gif = Gif.create(image_path: Giphy.random(search_term).image_url.to_s, category_id: @category.id)
    redirect_to admin_gifs_path(anchor: @category.search_term)
  else
    flash.now[:info] = "New GIF must be from a category that has already been created."
    render :new
  end
end


def destroy
  @gif = Gif.find(params[:id])
  @gif.destroy
  redirect_to admin_gifs_path
end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.where(admin: false)
    @admins = User.where(admin: true)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
      flash[:success] = "New user created!"
    elsif User.find_by(email: @user.email)
      flash.now[:info] = "User already exists, please try again"
      render :new
    else
      flash.now[:warning] = "Please fill in all fields before submitting new user"
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user
  end

  def current_admin?
    current_user.admin
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
      flash[:success] = "New category created!"
    else
      flash.now[:error] = "Category exists, please try again"
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
    flash[:success] = "Category successfully deleted!"
  end

  private

  def category_params
    params.require(:category).permit(:search_term)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def new

  end

  def create
    @gif = Gif.find(params[:gif_id])
    @favorite = Favorite.create(user_id: current_user.id, gif_id: @gif.id)
    redirect_to user_path(current_user)
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to user_path(current_user)
  end
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  require 'giphy'

  before_action :require_login, only: [:index, :new, :create, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @gif = Gif.new

  end

  def show
    @gif = Gif.find(params[:id])
  end



  private

  def require_login
    unless session[:user_id]
      flash[:warning] = "You must be logged in to do that!"
      redirect_to login_path
    end
  end

  # def require_admin
  #   if session[:user_id]
  #
  # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.authenticate(params[:password]) && @user.admin == true
      flash[:success] = "Successfully logged in as admin!"
      session[:user_id] = @user.id
      redirect_to admin_user_path(@user)
    elsif @user.authenticate(params[:password])
      flash[:success] = "Successfully logged in!"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:warning] = "Incorrect password, please try again"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = "You have successfully logged out!"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]
  def new
    @user = User.new
  end

  def index
  end

  def create
    @user = User.new(user_params)
    if @user.save && logged_in?
      redirect_to user_path(current_user)
      flash[:success] = "New user created!"
    elsif @user.save && !logged_in?
      redirect_to login_path
      flash[:success] = "New user created! Please log in."
    elsif User.find_by(email: @user.email)
      redirect_to login_path
      flash[:info] = "User already exists, please log in"
    else
      flash.now[:info] = "Please fill in all fields before submitting new user"
      render :new
    end
  end

  def show
    if current_user && User.find(params[:id]) == current_user
      @user = current_user
    else
      render file: '/public/404'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :admin)
  end

  def require_login
    unless session[:user_id]
      flash[:danger] = "You must be logged in to do that!"
      redirect_to login_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1>All Categories</h1>
<% @categories.each do |category| %>
  <div class="category_<%= category.id %>">
    <h3><%= link_to category.search_term, admin_gifs_path(anchor: category.search_term) %>: <%= category.gifs.count %> GIFs
    <%= link_to "Delete", admin_category_path(category), method: :delete, class: "btn btn-danger" %></h3>
  </div>
<% end %>

<%= link_to "Back to my admin page", admin_user_path(current_user) %>

app/views/admin/categories/new.html.erb
<h1>Create a new category:</h1>

<%= form_for [:admin, @category] do |f| %>

<%= f.label :search_term %>
<%= f.text_field :search_term %></p>

<%= f.submit "Create Category", class: "btn btn-success" %>

<% end %>

app/views/admin/gifs/index.html.erb
<div class="container">
<% @categories.each do |category| %>
  <h1 style="font-weight: lighter" id="<%= category.search_term%>"><%= category.search_term.capitalize %></h1>
  <div class="row">
    <% category.gifs.each do |gif| %>
      <div class="col-md-4">
        <div class="thumbnail" style="background-color: #edf4f4; padding:10px">
      <%= image_tag(gif.image_path) %>
      <div class="caption">
        <%= link_to "Delete", admin_gif_path(gif), method: :delete, class: "btn btn-danger" %>
        <% if !Favorite.find_by(user_id: current_user.id, gif_id: gif.id) %>
        <%= link_to 'Favorite', {:controller => "favorites",
                     :action => "create",
                     :user_id => current_user.id,
                     :gif_id => gif.id},
                     :method => "post",
                      class: "btn btn-success"%>
      <% else %>
        <span class="btn btn-success", disabled="disabled">Already a favorite!</span>
        <% end %></div></div></div>
      <% end %>
    </div><hr>
    <% end %>


<%= link_to "Back to my admin page", admin_user_path(current_user) %>
</div>

app/views/admin/gifs/new.html.erb
<h1>Generate a New GIF</h1>
<div class="col-md-6"><%= form_tag admin_gifs_path, :method => 'post' do %>

    <%= text_field_tag :search_term, nil, placeholder: "Category" %></p>
    <%= submit_tag "Generate Gif", class: "btn btn-success" %>
  </p>
<% end %></div>
<div class="col-md-6"><p>Available Categories</p>
  <% @categories.each do |category| %>
    <%= category.search_term %><br>
  <% end %>

<%= link_to "Create a new Category", new_admin_category_path %>

app/views/admin/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <p><h3><%= user.username %>:</h3> </p><p><%= link_to "Email", "mailto: #{user.email}", class: "btn btn-primary" %>
  <%= link_to "Delete", admin_user_path(user), method: :delete, class: "btn btn-danger" %></p><hr>
<% end %>

<h1>All Admins</h1>

<% @admins.each do |admin| %>
  <h3><%= admin.username %></h3><p> <%= link_to "Email", "mailto: #{admin.email}", class: "btn btn-primary" %></p>
<% end %><hr>

<%= link_to "Back to my admin page", admin_user_path(current_user) %>

app/views/admin/users/new.html.erb
<h1>Create a new user:</h1>

<%= form_for [:admin, @user] do |f| %>

<%= f.label :username %>
<%= f.text_field :username %></p>

<%= f.label :email %>
<%= f.text_field :email %></p>

<%= f.label :password %>
<%= f.password_field :password %></p>

<%= f.label :admin %> 
<%= f.check_box :admin %></p>

<%= f.submit "Submit", class: "btn btn-success" %>

<% end %>

app/views/admin/users/show.html.erb
<h1>Welcome Admin!</h1>
<p><%= link_to "Add user", new_admin_user_path %></p>
<p><%= link_to "View all users", admin_users_path %></p>
<p><%= link_to "Add new category", new_admin_category_path %></p>
<p><%= link_to "Generate new GIF", new_admin_gif_path %></p>

app/views/categories/index.html.erb
<h1>All Categories</h1>
<% @categories.each do |category| %>
  <div class="category_<%= category.id %>">
    <%= category.search_term %>
    <%= link_to "Delete", category_path(category), method: :delete %>
  </div>
<% end %>

app/views/categories/new.html.erb
<h1>Create a new category:</h1>

<%= form_for @category do |f| %>

<%= f.label :search_term %>
<%= f.text_field :search_term %>

<%= f.submit %>

<% end %>

app/views/gifs/index.html.erb
<div class="container">
<% @categories.each do |category| %>
  <h1 style="font-weight: lighter"><%= category.search_term.capitalize %></h1>
  <div class="row well">
    <% category.gifs.each do |gif| %>
      <div class="col-md-4">
        <div class="thumbnail" style="background-color: #edf4f4; padding:10px">
      <%= image_tag(gif.image_path) %>
      <div class="caption">
        <% if !Favorite.find_by(user_id: current_user.id, gif_id: gif.id) %>
        <%= link_to 'Favorite', {:controller => "favorites",
                     :action => "create",
                     :user_id => current_user.id,
                     :gif_id => gif.id},
                     :method => "post",
                      class: "btn btn-success"%>
      <% else %>
        <span class="btn btn-success", disabled="disabled">Already a favorite!</span>
        <% end %></div></div></div>
      <% end %></div><hr>
    <% end %>
  </div>

app/views/gifs/show.html.erb
<%= image_tag(@gif.image_path) %>
<% if !Favorite.find_by(user_id: current_user.id, gif_id: @gif.id) %>
  <%= link_to 'Favorite me!', {:controller => "favorites",
                       :action => "create",
                       :user_id => current_user.id,
                       :gif_id => @gif.id},
                       :method => "post" %>
  <% else %>
  <p>Already a favorite!</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GifGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 50px" class="text-center">
  <% flash.each do |type, msg| %>
    <%= content_tag :div, msg, class:"alert alert-#{type} alert-dismissible", role: "alert" %>

  <% end %>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">GIF Generator</a>
      </div>


      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if current_user && !current_user.admin %>
            <li><%= link_to "Home", root_path %></span></a></li>
            <li><%= link_to "All GIFs", gifs_path %></li>
            <li><%= link_to "Favorites", user_path(current_user) %></li>
          <% elsif current_user && current_user.admin %>
            <li><%= link_to "Home", admin_user_path(current_user) %></span></a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Add New User", new_admin_user_path %></li>
                <li><%= link_to "View All Users", admin_users_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">GIFs <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Generate New GIF", new_admin_gif_path %></li>
                <li><%= link_to "All GIFs", admin_gifs_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "All Categories", admin_categories_path %></li>
                <li><%= link_to "Create New Category", new_admin_category_path %></li>
              </ul>
            </li>
            <li><%= link_to "Favorites", user_path(current_user) %></li>
          <% else %>
            <li><%= link_to "Home", root_path %></span></a></li>
            <li><%= link_to "Create Account", new_user_path %>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if logged_in? %>
              <%= link_to "Logout #{current_user.username}", logout_path %>
            <% else %>
              <%= link_to "Login", login_path %>
            <% end %>
          </li>
        </ul>

      </div>
    </div>
  </nav>

<%= yield %>


</body>
</html>

app/views/users/index.html.erb
<% if current_user %>
  <%= "Welcome #{current_user.username}!" %>
<% else %>
  <%= "Welcome Guest!" %>
<% end %>
<hr>

<%= image_tag "#{Giphy.random("cat").image_url.to_s}" %>

app/views/users/new.html.erb
<h1>Create a new user:</h1>

<div class="row well"><%= form_for @user do |f| %>

<%= f.label :username %>
<%= f.text_field :username %></p>

<%= f.label :email %>
<%= f.text_field :email %></p>

<%= f.label :password %>
<%= f.password_field :password %></p>

<%= f.submit %>

<% end %></div>

app/views/users/show.html.erb
<div class="container">
<h1 style="font-weight:lighter"><%= @user.username.capitalize %>'s Favorites!</h1>
<div class="row">
<% @user.favorites.each do |fav| %>
  <div class="col-md-4">
    <div class="thumbnail" style="background-color: #edf4f4; padding:10px">
    <%= image_tag(Gif.find_by(id: fav.gif_id).image_path) %>
    <div class="caption">
    <%= link_to "Unfavorite", favorite_path(fav), method: :delete, class: "btn btn-warning" %>
  </div></div></div>
    <% end %>
</div>
<p><%= link_to "Back to all GIFs", gifs_path %><p>
</div>